#!/usr/bin/python
import yaml
import sys
from termcolor import colored
from _lib.get_input import get_tests
from _lib.selenium_driver import DRIVER, open_browser_instance, teardown, clear_screen, find_element
from _lib.auto_load_tests import run_test

try:
  with open('tests.yaml', 'r') as f:
    tests = yaml.load(f)
except Exception as e:
  print(e)
  sys.exit()

if ('tests' in tests) and ('url' in tests):
  TESTS = tests['tests']
  URL = tests['url']
else:
  print(colored('tests.yaml is missing "url" or "tests". Both are required.', 'red'))
  sys.exit()


def tests_run(tests=list(TESTS.keys())):
    print(colored('Starting browser instance\n', 'yellow'))
    open_browser_instance(driver=DRIVER, url=URL)
    for test in tests:
        if test == 'All':
            continue
        run_test(test=test, driver=DRIVER, tests=TESTS, find_element=find_element)


def run():
    clear_screen()
    print(colored('\nPlease use spacebar to make multiple selection\n', 'yellow'))
    tests_run(get_tests(TESTS))
    print(colored('\nAll Tests complete. Terminating the Browser instance.\n', 'blue'))
    # teardown(DRIVER)


if __name__ == "__main__":
  run()
